version: "4"
name: Three-Tiers Architecture
canonical: three-tiers
author: "cycloid-fbh"
# Fill in the stack details.
description: "Allow you to deploy Three-Tiers Architecture."
image: https://static.cycloid.io/3tiers.svg
keywords:
  - "azure"
  - "aws"
  - "digit"
  - "demo"
  - "three-tiers"
template: false
config:
  aws:
    name: "AWS"
    cloud_provider: aws
    pipeline:
      pipeline:
        path: "pipeline/pipeline.yml"
      variables:
        path: "pipeline/variables.yml"
        destination: "($ .config_root $)/pipeline/variables.yml"

  azure:
    name: "Azure"
    cloud_provider: azurerm
    pipeline:
      pipeline:
        path: "pipeline/pipeline.yml"
      variables:
        path: "pipeline/variables.yml"
        destination: "($ .config_root $)/pipeline/variables.yml"
