---
resources:
- name: stack
  type: git
  icon: github-circle
  source:
    uri: ($ .catalog_repository_url $)
    branch: ($ .catalog_repository_branch $)
    ($- if eq .catalog_repository_credential_type "basic_auth" $)
    username: ((($ .catalog_repository_credential_path $).username))
    password: ((($ .catalog_repository_credential_path $).password))
    ($- end $)
    ($- if eq .catalog_repository_credential_type "ssh" $)
    private_key: ((($ .catalog_repository_credential_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .stack_path $)/pipeline/*

jobs:
- name: deploy
  build_logs_to_retain: 10
  plan:
  - do:
    - get: stack
      trigger: true
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          dir: ""
          path: bash
          args:
            - "-ec"
            - |
              cd stack/($ .stack_path $)/pipeline/scripts
              bash deploy.sh
        inputs:
        - name: stack
          path: "stack"
        params:
          USE_CASE: ($ .use_case $)
          CY_ORG: ($ .org $)
          CY_PROJECT: ($ .project $)
          CY_ENV: ($ .environment $)
          CY_COMPONENT: ($ .component $)
          CY_COMPONENT_NAME: ($ .component_name $)
          CY_CONSOLE_URL: ($ .console_url $)
          CY_API_URL: ($ .api_url $)
          CY_API_KEY: ((admin-api-key.password))
          CY_STACKFORMS_VARS:
            "Service configuration":
              Support:
                digit_support_level: ((digit_support_level))
                digit_uptime: ((digit_uptime))
                digit_recover_time: ((digit_recover_time))
          ($- if eq .use_case "aws" $)
            Configurations:
              Access:
                aws_default_region: ((aws_default_region))
              Database:
                postgres_engine_version: ((postgres_engine_version))
                postgres_type: ((postgres_type))
              Backup:
                postgres_backup_retention: ((postgres_backup_retention))
              Infrastructure:
                database_inventory: "($ .project $)-($ .environment $)-database"
                network_inventory: "($ .project $)-($ .environment $)-network"
              Application:
                demo_gitlab_project: ((demo_gitlab_project))
                web_image_version: ((web_image_version))
          ($- end $)
          ($- if eq .use_case "azure" $)
            Configurations:
              Access:
                location: ((location))
              Infrastructure:
                virtual_network_name: "main-network"
              Database:
                sku: ((sku))
                engine_version: ((engine_version))
              Backup:
                backup_retention_days: ((backup_retention_days))
              Application:
                demo_gitlab_project: ($ .project $)
                web_image_version: ((web_image_version))
          ($- end $)

- name: destroy
  build_logs_to_retain: 10
  plan:
  - do:
    - get: stack
      trigger: false
    - task: destroy
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          dir: ""
          path: bash
          args:
            - "-ec"
            - |
              cd stack/($ .stack_path $)/pipeline/scripts
              bash destroy.sh
        inputs:
        - name: stack
          path: "stack"
        params:
          CY_ORG: ($ .org $)
          CY_PROJECT: ($ .project $)
          CY_ENV: ($ .environment $)
          CY_COMPONENT: ($ .component $)
          CY_COMPONENT_NAME: ($ .component_name $)
          CY_API_URL: ($ .api_url $)
          CY_API_KEY: ((admin-api-key.password))

groups:
- name: overview
  jobs:
  - deploy
- name: destroy
  jobs:
  - destroy
