---
resources:
- name: cycloid-toolkit
  type: registry-image
  icon: github
  source:
    repository: cycloid/cycloid-toolkit
    tag: latest

- name: stack
  type: git
  icon: github-circle
  source:
    uri: ($ .catalog_repository_url $)
    branch: ($ .catalog_repository_branch $)
    ($- if eq .catalog_repository_cred_type "basic_auth" $)
    username: ((($ .catalog_repository_cred_path $).username))
    password: ((($ .catalog_repository_cred_path $).password))
    ($- end $)
    ($- if eq .catalog_repository_cred_type "ssh" $)
    private_key: ((($ .catalog_repository_cred_path $).ssh_key))
    ($- end $)
    paths:
    - ($ .stack_path $)/*

jobs:
- name: deploy
  build_logs_to_retain: 10
  plan:
  - do:
    - get: stack
      trigger: true
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          dir: stack/pipeline
          path: deploy.sh
        inputs:
        - name: stack
          path: "stack"
        params:
          USE_CASE: ($ .use_case $)
          CY_ORG: ($ .org $)
          CY_PROJECT: ($ .project $)
          CY_ENV: ($ .environment $)
          CY_COMPONENT: ($ .component $)
          CY_COMPONENT_NAME: ($ .component_name $)
          CY_API_URL: ($ .api_url $)
          CY_API_KEY: "TODO"
          CY_STACKFORMS_VARS:
          ($- if eq .use_case "aws" $)
            Configurations:
              Access:
                aws_default_region: ((aws_default_region))
                network_inventory: ((network_inventory))
              Database:
                postgres_engine_version: ((postgres_engine_version))
                postgres_type: ((postgres_type))
                postgres_backup_retention: ((postgres_backup_retention))
              Infrastructure:
                database_inventory: # arn ?
                demo_gitlab_project: ((demo_gitlab_project))
                web_image_version: ((web_image_version))
          ($- end $)
          ($- if eq .use_case "azure" $)
            "Cloud provider":
              Settings:
                location: ((location))
            Database:
              Settings:
                virtual_network_name: "main-network"
                sku: ((db_sku))
                backup_retention_days: ((backup_retention_days))
                user: petclinic
                database: petclinic
                engine_version: ((engine_version))
                resource_group_name: ($ .organization $)-($ .project $)-($ .environment $)
            Configuration:
              Infrastructure:
                db_name: "postgres-${CY_PROJECT}-${CY_ENV}"
              Application:
                demo_gitlab_project: ($ .project $)
                web_image_version: ((web_image_version))
          ($- end $)

- name: destroy
  build_logs_to_retain: 10
  plan:
  - do:
    - get: stack
      trigger: true
    - task: destroy
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          dir: stack/pipeline
          path: destroy.sh
        inputs:
        - name: stack
          path: "stack"
        params:
          CY_ORG: ($ .org $)
          CY_PROJECT: ($ .project $)
          CY_ENV: ($ .environment $)
          CY_COMPONENT: ($ .component $)
          CY_COMPONENT_NAME: ($ .component_name $)
          CY_API_URL: ($ .api_url $)
          CY_API_KEY: "TODO"

groups:
- name: overview
  jobs:
  - deploy
- name: destroy
  jobs:
  - destroy
