version: "4"
name: "Batch"
canonical: batch
description: |
  Stack that batch components
template: false
image: https://static.cycloid.io/sourcetree.svg
author: "cycloid-fbh"
config:
  aws:
    name: "AWS"
    cloud_provider: aws
    pipeline: &pp
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: "pipeline/variables.yml"
        destination: "($ .config_root $)/pipeline/variables.yml"
  azure:
    name: "Azure"
    cloud_provider: azurerm
    pipeline: *pp
