---
# Configuration of the Cycloid stack
version: "4"
name: "Scaffold Software Project"
canonical: demo-git-scaffold
author: Cycloid
description: |
  Create a Git repository and scaffold a new project with my organization best practices and security rules.
image: https://static.cycloid.io/gitlab.svg
keywords:
  - "VueJS"
  - "git"
  - "IDP"
  - "Internal Developer Platform"
  - "developer"
  - "application"
technologies:
  - technology: terraform
    version: 1.11.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: "($ .config_root $)/pipeline/variables.yml"
