---
version: "2"
use_cases:
  - name: default
    sections:
      - name: config
        groups:
          - name: Scaffolding Template
            technologies: [pipeline]
            vars:
              - name: "Gitlab project name"
                description: "The Gitlab project name to use"
                widget: simple_text
                key: target_project
                type: "string"

              - name: "Project Type"
                description: "Specifies the technology stack used in the project"
                key: scaffolding_template
                widget: dropdown
                required: true
                type: string
                values:
                  - Angular
                  - Java
                  - NodeJS
                  - Python
                  - React
                # default: "Java"

              - name: "Environments"
                description: "Specifies the environments to provision in the project"
                key: target_envs
                widget: dropdown
                required: true
                type: array
                values:
                  - Prod-AWS
                  - Prod-Azure
                  - UAT-AWS
                  - UAT-Azure
                  - Dev-AWS
                  - Dev-Azure
                widget_config:
                  multiselect: true
