resources:
- name: git_config
  type: git
  icon: github-circle
  source:
    uri: ($ .cr_url $)
    branch: ($ .cr_branch $)
    ($- if eq .cr_cred_type "basic_auth" $)
    username: ((($ .cr_cred_path $).username))
    password: ((($ .cr_cred_path $).password))
    ($- end $)
    ($- if eq .cr_cred_type "ssh" $)
    private_key: ((($ .cr_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .config_root $)/pipeline/*

jobs:
- name: scaffold-git
  build_logs_to_retain: 3
  plan:
  - do:
    - get: git_config
      trigger: true
    - task: scaffold-git
      config:
          platform: linux
          image_resource:
              type: docker-image
              source: {repository: busybox}
          run:
            path: /bin/sh
            args:
            - -ec
            - |
              echo "scaffold git"


    - task: create-project-env
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          path: bash
          args:
            - "-ec"
            - |
              MAX_RETRIES=3
              COUNT=0
              while [ $COUNT -lt $MAX_RETRIES ]; do
                echo "Create Projecy: ${TARGET_PROJECT}"
                cy project create --project "${TARGET_PROJECT}" 2>/dev/null

                if [ $? -eq 0 ]; then
                  echo "Component created successfully."
                  break
                fi

                COUNT=$((COUNT + 1))
                echo "Attempt $COUNT failed... retrying"

                sleep 1
              done
              echo "  Create Environments:"
              IFS=$'\n'; for env in $(echo $TARGET_ENVS | jq -r .[]);do
                echo "    - $env"
                cy environment create --env "$env" 2>/dev/null
              done
              echo "https://${CONSOLE_URL}/organizations/${CY_ORG}/projects/${PROJECT}"

        params:
          CONSOLE_URL: ($ .console_url $)
          CY_API_KEY: ((admin-api-key.password))
          CY_ORG: ($ .organization $)
          CY_VERSION: latest
          TARGET_PROJECT: ((target_project))
          TARGET_ENVS: ((target_envs))
