resources:
- name: git_config
  type: git
  icon: github-circle
  source:
    uri: ($ .cr_url $)
    branch: ($ .cr_branch $)
    ($- if eq .cr_cred_type "basic_auth" $)
    username: ((($ .cr_cred_path $).username))
    password: ((($ .cr_cred_path $).password))
    ($- end $)
    ($- if eq .cr_cred_type "ssh" $)
    private_key: ((($ .cr_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .org $)/($ .project $)/($ .env $)/($ .component $)/pipeline/*

jobs:
- name: scaffold-git
  build_logs_to_retain: 3
  plan:
  - do:
    - get: git_config
      trigger: true
    - task: scaffold-git
      config:
          platform: linux
          image_resource:
              type: docker-image
              source: {repository: busybox}
          run:
            path: /bin/sh
            args:
            - -ec
            - |
              echo scaffold git