# Define the stack configuration form and organize inputs of various types into sections and groups.
# See: https://docs.staging.cycloid.io/deploy/stackforms/file-format.html
use_cases:
  - name: aws
    sections:
      - name: Configurations
        groups:
          - name: Access
            technologies: [pipeline]
            vars:
              - name: "Aws region"
                key: aws_default_region
                type: string
                widget: auto_complete
                values:
                  [
                    "eu-north-1",
                    "ap-south-1",
                    "eu-west-3",
                    "eu-west-2",
                    "eu-west-1",
                    "ap-northeast-2",
                    "ap-northeast-1",
                    "sa-east-1",
                    "ca-central-1",
                    "ap-southeast-1",
                    "ap-southeast-2",
                    "eu-central-1",
                    "us-east-1",
                    "us-east-2",
                    "us-west-1",
                    "us-west-2",
                  ]
                default: "eu-west-1"
              # - name: "AWS access key"
              #   description: "AWS access key which should be used"
              #   key: aws_cred
              #   type: string
              #   widget: cy_cred
              #   widget_config:
              #     display_keys: false
              #     cred_types: [aws]
              #   default: "((aws-production))"

  - name: azure
    sections:
      - name: Configurations
        groups:
          - name: Access
            technologies: [terraform]
            vars:
              - name: "Azure Region"
                description: "Which region should this be deployed."
                key: location
                type: string
                widget: radios
                values: ["West Europe", "Central Europe"]
                default: "West Europe"

          # - name: Access
          #   technologies: [pipeline]
          #   vars:
          #     - name: "Azure credential"
          #       description: "The azure credential containing subscription_id, tenant_id, client_id, client_secret"
          #       key: azure_cred
          #       type: string
          #       widget: cy_cred
          #       widget_config:
          #         display_keys: false
          #         cred_types: [azure]
          #       default: "((azure-production))"
