version: "4"
name: Microservices-Based Architecture
canonical: microservices-based
author: "florian"
# Fill in the stack details.
description: "Allow you to deploy Microservices-Based Architecture."
image: https://static.cycloid.io/microservice.png
keywords:
  - "azure"
  - "aws"
  - "digit"
  - "demo"
  - "microservices-based"
template: false
config:
  aws:
    name: "AWS"
    cloud_provider: aws
    pipeline:
      pipeline:
        path: "pipeline/pipeline.yml"
      variables:
        path: "pipeline/variables.sample.yml"
        destination: "($ .config_root $)/pipeline/variables.yml"

  azure:
    name: "Azure"
    cloud_provider: azurerm
    pipeline:
      pipeline:
        path: "pipeline/pipeline.yml"
      variables:
        path: "pipeline/variables.sample.yml"
        destination: "($ .config_root $)/pipeline/variables.yml"
