# Define the stack configuration form and organize inputs of various types into sections and groups.
# See: https://docs.staging.cycloid.io/deploy/stackforms/file-format.html
use_cases:
  - name: aws
    sections:
      - name: Configurations
        groups:
          - name: Infrastructure
            technologies: [pipeline]
            vars:
              - name: "Database"
                description: "The database to use"
                key: database_inventory
                type: "string"
                widget: cy_inventory_resource
                widget_config:
                  attribute: arn
                  filters:
                    provider: aws
                    project: ($ .project $)
                    environment: ($ .environment $)
                    type: aws_rds_cluster
                    # attributes: 'arn[rlike]="*:${aws_default_region}:*'
                required: true

          - name: Application
            technologies: [pipeline]
            vars:
              - name: "Gitlab Project"
                description: "Gitlab project associeted to the application"
                key: demo_gitlab_project
                widget: simple_text
                type: string
                default: ($ .project $)

              - name: "Application Version"
                description: "Version of your application to deploy"
                key: web_image_version
                widget: simple_text
                type: string
                default: "latest"

  - name: azure
    sections:
      - name: Configuration
        groups:
          - name: Infrastructure
            technologies: [terraform]
            vars:
              - name: "Database"
                key: db_name
                type: string
                widget: cy_inventory_resource
                widget_config:
                  attribute: name
                  filters:
                    project: ($ .project $)
                    environment: ($ .environment $)
                    provider: azurerm
                    type: azurerm_postgresql_flexible_server
                required: true
                default: "db-postgres"

          - name: Application
            technologies: [pipeline]
            vars:
              - name: "Gitlab Project"
                description: "Gitlab project associeted to the application"
                key: demo_gitlab_project
                widget: simple_text
                type: string
                default: ($ .project $)

              - name: "Application Version"
                description: "Version of your application to deploy"
                key: web_image_version
                widget: simple_text
                type: string
                default: "latest"

