set dotenv-load := true
set dotenv-filename := ".env"

export CY_API_URL := "https://api.us.cycloid.io"
export CY_API_KEY := `op read "op://Cycloid/API_saas_us_digital_services/identifiant"`
export AZURE_CRED_JSON := `cy cred get --canonical azure_demo_automation -o json`

# export ARM_CLIENT_ID := shell("echo $@ | jq -r .raw.client_id", AZURE_CRED_JSON)
# export ARM_TENANT_ID := shell("echo $@ | jq -r .raw.tenant_id", AZURE_CRED_JSON)
# export ARM_CLIENT_SECRET := shell("echo $@ | jq -r .raw.client_secret", AZURE_CRED_JSON)

export ARM_SUBSCRIPTION_ID := shell("echo $@ | jq -r .raw.subscription_id", AZURE_CRED_JSON)
export TF_VAR_db_password := "DatabaseCoucou80"

playground: validate destroy output

init:
    terraform init

plan:
    terraform plan

apply:
    terraform apply -auto-approve 

destroy:
    terraform destroy -auto-approve 

validate:
    terraform validate

output:
    terraform output -json

tf *cmd:
    terraform {{ cmd }}

watch:
    watchexec -w Justfile -w . -e tf -c -- just
