---
version: '4'
name: IS
canonical: stack-is
status: private
author: Cycloid
description: |
  Create a new IS, including a Cycloid Organization with a new AWS S3 bucket as Terraform backend, and attach the git digit stacks to the new IS.
image: |
  https://upload.wikimedia.org/wikipedia/en/2/27/EU_flag_square.PNG
keywords:
  - cycloid
  - organization
  - git
  - s3
technologies:
  - technology: Cycloid
  - technology: GitHub
  - technology: S3
  - technology: terraform
    version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .org $)/($ .project $)/($ .env $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .org $)/($ .project $)/($ .env $)/($ .component $)/terraform/main.tf'