---
version: "2"
use_cases:
- name: default
  sections:
  - name: IS
    groups:
    - name: IS Specifications
      technologies: [pipeline]
      vars:
      - name: "IS Code"
        description: "The code of the IS."
        key: is_name
        widget: simple_text
        type: string
        validations: 
        - regexp: "^[a-z0-9-]+$" 
          error_message: "Please enter a valid IS name."
        required: true

    - name: Amazon Web Services
      technologies: [pipeline]
      vars:
      - name: "Provision an AWS account in the new IS?"
        description: "Shall we provision an AWS account in the new IS?"
        key: aws_sel
        widget: switch
        type: boolean
        value: false
        required: false

    - name: Amazon Web Services Specifications
      technologies: [pipeline]
      condition: "$aws_sel == true"
      vars:
      - name: "AWS Account"
        description: "The AWS account where the IS could deploy the infrastructure."
        key: aws_cred_child
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true

    - name: Azure
      technologies: [pipeline]
      vars:
      - name: "Provision an Azure account in the new IS?"
        description: "Shall we provision an Azure account in the new IS?"
        key: azure_sel
        widget: switch
        type: boolean
        value: false
        required: false

    - name: Azure Specifications
      technologies: [pipeline]
      condition: "$azure_sel == true"
      vars:
      - name: "Azure Account"
        description: "The Azure account where the IS could deploy the infrastructure."
        key: azure_cred_child
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true

    - name: Customer Admins
      technologies: [pipeline]
      vars:
      - name: "Customer Admins"
        description: "The Customer Admins who should given access to the IS. These users will be assigned the CustomerAdmin RBAC role."
        key: customer_admins
        type: array
        values:
        - {label: "Antony Di Maiolo", value: antony.dimaiolo@arhs-spikeseed.com}
        - {label: "Nicolas Buisson", value: nicolas.buisson@arhs-spikeseed.com}
        - {label: "Nicolas Labrot", value: nicolas.labrot@arhs-spikeseed.com}
        - {label: "Juan Gonzalez", value: juan-miguel.gonzalez-silva@ec.europa.eu}
        - {label: "Joseph Rizzo", value: joseph.rizzo@arhs-spikeseed.com}
        - {label: "Inalinda Fonseca", value: inalinda.fonseca@ext.ec.europa.eu}
        - {label: "Pierre Schrepel", value: pierre.schrepel@ext.ec.europa.eu}
        - {label: "Olivier de Turckheim", value: olivier.deturckheim@cycloid.io}
        widget: dropdown
        widget_config:
          multiselect: true

    - name: Customer Users
      technologies: [pipeline]
      vars:
      - name: "Customer Users"
        description: "The Customer Users who should given access to the IS. These users will be assigned the CustomerUser RBAC role."
        key: customer_users
        type: array
        values:
        - {label: "Antony Di Maiolo", value: antony.dimaiolo@arhs-spikeseed.com}
        - {label: "Nicolas Buisson", value: nicolas.buisson@arhs-spikeseed.com}
        - {label: "Nicolas Labrot", value: nicolas.labrot@arhs-spikeseed.com}
        - {label: "Juan Gonzalez", value: juan-miguel.gonzalez-silva@ec.europa.eu}
        - {label: "Joseph Rizzo", value: joseph.rizzo@arhs-spikeseed.com}
        - {label: "Inalinda Fonseca", value: inalinda.fonseca@ext.ec.europa.eu}
        - {label: "Pierre Schrepel", value: pierre.schrepel@ext.ec.europa.eu}
        - {label: "Olivier de Turckheim", value: olivier.deturckheim@cycloid.io}
        widget: dropdown
        widget_config:
          multiselect: true

